version: '3.7'

services:
  weblate:
    image: weblate/weblate:4.11.2-1
    tmpfs:
      - /app/cache
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./.weblate.env
    environment:
      WEBLATE_SITE_DOMAIN: weblate.${DOMAIN}
      WEBLATE_ENABLE_HTTPS: 1
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        - traefik.http.routers.imshop-202204__${PROJECT_NAME}.entrypoints=websecure
        - traefik.http.routers.imshop-202204__${PROJECT_NAME}.rule=Host(`weblate.${DOMAIN}`)
        - traefik.http.routers.imshop-202204__${PROJECT_NAME}.tls.certresolver=leresolver
        - traefik.http.services.imshop-202204__${PROJECT_NAME}.loadbalancer.server.port=8080
        - traefik.http.routers.imshop-202204__${PROJECT_NAME}.middlewares=imshop-auth@file
  database:
    image: postgres:14-alpine
    env_file:
      - ./.weblate.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
  cache:
    image: redis:6-alpine
    restart: always
    command: [ redis-server, --save, '60', '1' ]
    volumes:
      - redis-data:/data
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}

volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}

networks:
  default:
    external:
      name: proxy-main
